[package]
name = "image_color"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
reqwest = "0.11.10"
anyhow = "1.0.57"
tokio = { version = "1.19.2", features = ["full"] }
